UPDATE customer_address SET node=1 WHERE building=6559 AND property='Sun Prairie'
UPDATE customer_address SET node=1 WHERE building=6569 AND property='Sun Prairie'
UPDATE customer_address SET node=1 WHERE building=6579 AND property='Sun Prairie'
UPDATE customer_address SET node=1 WHERE building=6689 AND property='Sun Prairie'
UPDATE customer_address SET node=1 WHERE building=6699 AND property='Sun Prairie'
UPDATE customer_address SET node=19 WHERE address like '6701 HEMINGWAY%'
UPDATE customer_address SET node=2 WHERE building=6409 AND property like 'Sun P%'
UPDATE customer_address SET node=2 WHERE building=6419 AND property like 'Sun P%'
UPDATE customer_address SET node=2 WHERE building=6429 AND property like 'Sun P%'
UPDATE customer_address SET node=2 WHERE building=6539 AND property like 'Sun P%'
UPDATE customer_address SET node=2 WHERE building=6549 AND property like 'Sun P%'
UPDATE customer_address SET node=20 WHERE address like '6700 HEMINGWAY%'
UPDATE customer_address SET node=20 WHERE address like '6702 HEMINGWAY%'
UPDATE customer_address SET node=20 WHERE address like '6704 HEMINGWAY%'
UPDATE customer_address SET node=20 WHERE address like '6706 HEMINGWAY%'
UPDATE customer_address SET node=20 WHERE address like '6708 HEMINGWAY%'
UPDATE customer_address SET node=20 WHERE address like '6710 HEMINGWAY%'
UPDATE customer_address SET node=20 WHERE address like '6712 HEMINGWAY%'
UPDATE customer_address SET node=20 WHERE address like '6714 HEMINGWAY%'
UPDATE customer_address SET node=21 WHERE address like '6721 HEMINGWAY%'
UPDATE customer_address SET node=21 WHERE address like '6723 HEMINGWAY%'
UPDATE customer_address SET node=21 WHERE address like '6725 HEMINGWAY%'
UPDATE customer_address SET node=21 WHERE address like '6727 HEMINGWAY%'
UPDATE customer_address SET node=21 WHERE address like '6729 HEMINGWAY%'
UPDATE customer_address SET node=21 WHERE address like '6731 HEMINGWAY%'
UPDATE customer_address SET node=21 WHERE address like '6733 HEMINGWAY%'
UPDATE customer_address SET node=21 WHERE address like '6735 HEMINGWAY%'
UPDATE customer_address SET node=22 WHERE address like '6800 HEMINGWAY%'
UPDATE customer_address SET node=22 WHERE address like '6802 HEMINGWAY%'
UPDATE customer_address SET node=22 WHERE address like '6804 HEMINGWAY%'
UPDATE customer_address SET node=22 WHERE address like '6806 HEMINGWAY%'
UPDATE customer_address SET node=22 WHERE address like '6808 HEMINGWAY%'
UPDATE customer_address SET node=22 WHERE address like '6810 HEMINGWAY%'
UPDATE customer_address SET node=22 WHERE address like '6812 HEMINGWAY%'
UPDATE customer_address SET node=22 WHERE address like '6814 HEMINGWAY%'
UPDATE customer_address SET node=23 WHERE address like '6820 HEMINGWAY%'
UPDATE customer_address SET node=23 WHERE address like '6822 HEMINGWAY%'
UPDATE customer_address SET node=23 WHERE address like '6824 HEMINGWAY%'
UPDATE customer_address SET node=23 WHERE address like '6826 HEMINGWAY%'
UPDATE customer_address SET node=23 WHERE address like '6828 HEMINGWAY%'
UPDATE customer_address SET node=23 WHERE address like '6830 HEMINGWAY%'
UPDATE customer_address SET node=23 WHERE address like '6832 HEMINGWAY%'
UPDATE customer_address SET node=23 WHERE address like '6834 HEMINGWAY%'
UPDATE customer_address SET node=24 WHERE address like '6700 JAKE%'
UPDATE customer_address SET node=24 WHERE address like '6702 JAKE%'
UPDATE customer_address SET node=24 WHERE address like '6704 JAKE%'
UPDATE customer_address SET node=24 WHERE address like '6706 JAKE%'
UPDATE customer_address SET node=24 WHERE address like '6708 JAKE%'
UPDATE customer_address SET node=24 WHERE address like '6710 JAKE%'
UPDATE customer_address SET node=24 WHERE address like '6712 JAKE%'
UPDATE customer_address SET node=24 WHERE address like '6714 JAKE%'
UPDATE customer_address SET node=25 WHERE address like '6801 HEMINGWAY%'
UPDATE customer_address SET node=25 WHERE address like '6803 HEMINGWAY%'
UPDATE customer_address SET node=25 WHERE address like '6805 HEMINGWAY%'
UPDATE customer_address SET node=25 WHERE address like '6807 HEMINGWAY%'
UPDATE customer_address SET node=25 WHERE address like '6809 HEMINGWAY%'
UPDATE customer_address SET node=25 WHERE address like '6811 HEMINGWAY%'
UPDATE customer_address SET node=25 WHERE address like '6813 HEMINGWAY%'
UPDATE customer_address SET node=25 WHERE address like '6815 HEMINGWAY%'
UPDATE customer_address SET node=26 WHERE address like '6821 HEMINGWAY%'
UPDATE customer_address SET node=26 WHERE address like '6823 HEMINGWAY%'
UPDATE customer_address SET node=26 WHERE address like '6825 HEMINGWAY%'
UPDATE customer_address SET node=26 WHERE address like '6827 HEMINGWAY%'
UPDATE customer_address SET node=26 WHERE address like '6829 HEMINGWAY%'
UPDATE customer_address SET node=26 WHERE address like '6831 HEMINGWAY%'
UPDATE customer_address SET node=26 WHERE address like '6833 HEMINGWAY%'
UPDATE customer_address SET node=26 WHERE address like '6835 HEMINGWAY%'
UPDATE customer_address SET node=27 WHERE address like '6841 HEMINGWAY%'
UPDATE customer_address SET node=27 WHERE address like '6843 HEMINGWAY%'
UPDATE customer_address SET node=27 WHERE address like '6845 HEMINGWAY%'
UPDATE customer_address SET node=27 WHERE address like '6847 HEMINGWAY%'
UPDATE customer_address SET node=27 WHERE address like '6849 HEMINGWAY%'
UPDATE customer_address SET node=27 WHERE address like '6851 HEMINGWAY%'
UPDATE customer_address SET node=27 WHERE address like '6853 HEMINGWAY%'
UPDATE customer_address SET node=27 WHERE address like '6855 HEMINGWAY%'
UPDATE customer_address SET node=28 WHERE address like '6801 JAKE%'
UPDATE customer_address SET node=28 WHERE address like '6803 JAKE%'
UPDATE customer_address SET node=28 WHERE address like '6805 JAKE%'
UPDATE customer_address SET node=28 WHERE address like '6807 JAKE%'
UPDATE customer_address SET node=28 WHERE address like '6809 JAKE%'
UPDATE customer_address SET node=28 WHERE address like '6811 JAKE%'
UPDATE customer_address SET node=28 WHERE address like '6813 JAKE%'
UPDATE customer_address SET node=28 WHERE address like '6815 JAKE%'
UPDATE customer_address SET node=29 WHERE address like '6800 JAKE%'
UPDATE customer_address SET node=29 WHERE address like '6802 JAKE%'
UPDATE customer_address SET node=29 WHERE address like '6804 JAKE%'
UPDATE customer_address SET node=29 WHERE address like '6806 JAKE%'
UPDATE customer_address SET node=29 WHERE address like '6808 JAKE%'
UPDATE customer_address SET node=29 WHERE address like '6810 JAKE%'
UPDATE customer_address SET node=29 WHERE address like '6812 JAKE%'
UPDATE customer_address SET node=29 WHERE address like '6814 JAKE%'
UPDATE customer_address SET node=3 WHERE building=6367 AND property like 'Sun P%'
UPDATE customer_address SET node=3 WHERE building=6377 AND property like 'Sun P%'
UPDATE customer_address SET node=3 WHERE building=6387 AND property like 'Sun P%'
UPDATE customer_address SET node=30 WHERE address like '6821 JAKE%'
UPDATE customer_address SET node=30 WHERE address like '6823 JAKE%'
UPDATE customer_address SET node=30 WHERE address like '6825 JAKE%'
UPDATE customer_address SET node=30 WHERE address like '6827 JAKE%'
UPDATE customer_address SET node=30 WHERE address like '6829 JAKE%'
UPDATE customer_address SET node=30 WHERE address like '6831 JAKE%'
UPDATE customer_address SET node=30 WHERE address like '6833 JAKE%'
UPDATE customer_address SET node=30 WHERE address like '6835 JAKE%'
UPDATE customer_address SET node=31 WHERE address like '6101 BRETT%'
UPDATE customer_address SET node=31 WHERE address like '6103 BRETT%'
UPDATE customer_address SET node=31 WHERE address like '6105 BRETT%'
UPDATE customer_address SET node=31 WHERE address like '6107 BRETT%'
UPDATE customer_address SET node=31 WHERE address like '6109 BRETT%'
UPDATE customer_address SET node=31 WHERE address like '6111 BRETT%'
UPDATE customer_address SET node=31 WHERE address like '6113 BRETT%'
UPDATE customer_address SET node=31 WHERE address like '6115 BRETT%'
UPDATE customer_address SET node=32 WHERE address like '6100 BRETT%'
UPDATE customer_address SET node=32 WHERE address like '6102 BRETT%'
UPDATE customer_address SET node=32 WHERE address like '6104 BRETT%'
UPDATE customer_address SET node=32 WHERE address like '6106 BRETT%'
UPDATE customer_address SET node=32 WHERE address like '6108 BRETT%'
UPDATE customer_address SET node=32 WHERE address like '6110 BRETT%'
UPDATE customer_address SET node=32 WHERE address like '6112 BRETT%'
UPDATE customer_address SET node=32 WHERE address like '6114 BRETT%'
UPDATE customer_address SET node=33 WHERE address like '6121 BRETT%'
UPDATE customer_address SET node=33 WHERE address like '6123 BRETT%'
UPDATE customer_address SET node=33 WHERE address like '6125 BRETT%'
UPDATE customer_address SET node=33 WHERE address like '6127 BRETT%'
UPDATE customer_address SET node=33 WHERE address like '6129 BRETT%'
UPDATE customer_address SET node=33 WHERE address like '6131 BRETT%'
UPDATE customer_address SET node=33 WHERE address like '6133 BRETT%'
UPDATE customer_address SET node=33 WHERE address like '6135 BRETT%'
UPDATE customer_address SET node=34 WHERE address like '6200 BRETT%'
UPDATE customer_address SET node=34 WHERE address like '6202 BRETT%'
UPDATE customer_address SET node=34 WHERE address like '6204 BRETT%'
UPDATE customer_address SET node=34 WHERE address like '6206 BRETT%'
UPDATE customer_address SET node=34 WHERE address like '6208 BRETT%'
UPDATE customer_address SET node=34 WHERE address like '6210 BRETT%'
UPDATE customer_address SET node=34 WHERE address like '6212 BRETT%'
UPDATE customer_address SET node=34 WHERE address like '6214 BRETT%'
UPDATE customer_address SET node=35 WHERE address like '6201 BRETT%'
UPDATE customer_address SET node=35 WHERE address like '6203 BRETT%'
UPDATE customer_address SET node=35 WHERE address like '6205 BRETT%'
UPDATE customer_address SET node=35 WHERE address like '6207 BRETT%'
UPDATE customer_address SET node=35 WHERE address like '6209 BRETT%'
UPDATE customer_address SET node=35 WHERE address like '6211 BRETT%'
UPDATE customer_address SET node=35 WHERE address like '6213 BRETT%'
UPDATE customer_address SET node=35 WHERE address like '6215 BRETT%'
UPDATE customer_address SET node=36 WHERE address like '6220 BRETT%'
UPDATE customer_address SET node=36 WHERE address like '6222 BRETT%'
UPDATE customer_address SET node=36 WHERE address like '6224 BRETT%'
UPDATE customer_address SET node=36 WHERE address like '6226 BRETT%'
UPDATE customer_address SET node=36 WHERE address like '6228 BRETT%'
UPDATE customer_address SET node=36 WHERE address like '6230 BRETT%'
UPDATE customer_address SET node=36 WHERE address like '6232 BRETT%'
UPDATE customer_address SET node=36 WHERE address like '6234 BRETT%'
UPDATE customer_address SET node=37 WHERE address like '6221 BRETT%'
UPDATE customer_address SET node=37 WHERE address like '6223 BRETT%'
UPDATE customer_address SET node=37 WHERE address like '6225 BRETT%'
UPDATE customer_address SET node=37 WHERE address like '6227 BRETT%'
UPDATE customer_address SET node=37 WHERE address like '6229 BRETT%'
UPDATE customer_address SET node=37 WHERE address like '6231 BRETT%'
UPDATE customer_address SET node=37 WHERE address like '6233 BRETT%'
UPDATE customer_address SET node=37 WHERE address like '6235 BRETT%'
UPDATE customer_address SET node=38 WHERE address like '6300 BRETT%'
UPDATE customer_address SET node=38 WHERE address like '6302 BRETT%'
UPDATE customer_address SET node=38 WHERE address like '6304 BRETT%'
UPDATE customer_address SET node=38 WHERE address like '6306 BRETT%'
UPDATE customer_address SET node=38 WHERE address like '6308 BRETT%'
UPDATE customer_address SET node=38 WHERE address like '6310 BRETT%'
UPDATE customer_address SET node=38 WHERE address like '6312 BRETT%'
UPDATE customer_address SET node=38 WHERE address like '6314 BRETT%'
UPDATE customer_address SET node=39 WHERE address like '6921 HEMINGWAY%'
UPDATE customer_address SET node=39 WHERE address like '6923 HEMINGWAY%'
UPDATE customer_address SET node=39 WHERE address like '6925 HEMINGWAY%'
UPDATE customer_address SET node=39 WHERE address like '6927 HEMINGWAY%'
UPDATE customer_address SET node=39 WHERE address like '6929 HEMINGWAY%'
UPDATE customer_address SET node=39 WHERE address like '6931 HEMINGWAY%'
UPDATE customer_address SET node=39 WHERE address like '6933 HEMINGWAY%'
UPDATE customer_address SET node=39 WHERE address like '6935 HEMINGWAY%'
UPDATE customer_address SET node=4 WHERE building=6001 AND property like 'Sun P%'
UPDATE customer_address SET node=4 WHERE building=6017 AND property like 'Sun P%'
UPDATE customer_address SET node=4 WHERE building=6127 AND property like 'Sun P%'
UPDATE customer_address SET node=4 WHERE building=6137 AND property like 'Sun P%'
UPDATE customer_address SET node=4 WHERE building=6147 AND property like 'Sun P%'
UPDATE customer_address SET node=4 WHERE building=6257 AND property like 'Sun P%'
UPDATE customer_address SET node=40 WHERE address like '6940 HEMINGWAY%'
UPDATE customer_address SET node=40 WHERE address like '6942 HEMINGWAY%'
UPDATE customer_address SET node=40 WHERE address like '6944 HEMINGWAY%'
UPDATE customer_address SET node=40 WHERE address like '6946 HEMINGWAY%'
UPDATE customer_address SET node=40 WHERE address like '6948 HEMINGWAY%'
UPDATE customer_address SET node=40 WHERE address like '6950 HEMINGWAY%'
UPDATE customer_address SET node=40 WHERE address like '6952 HEMINGWAY%'
UPDATE customer_address SET node=40 WHERE address like '6954 HEMINGWAY%'
UPDATE customer_address SET node=41 WHERE address like '6920 HEMINGWAY%'
UPDATE customer_address SET node=41 WHERE address like '6922 HEMINGWAY%'
UPDATE customer_address SET node=41 WHERE address like '6924 HEMINGWAY%'
UPDATE customer_address SET node=41 WHERE address like '6926 HEMINGWAY%'
UPDATE customer_address SET node=41 WHERE address like '6928 HEMINGWAY%'
UPDATE customer_address SET node=41 WHERE address like '6930 HEMINGWAY%'
UPDATE customer_address SET node=41 WHERE address like '6932 HEMINGWAY%'
UPDATE customer_address SET node=41 WHERE address like '6934 HEMINGWAY%'
UPDATE customer_address SET node=42 WHERE building='6900' AND property='Mansions'
UPDATE customer_address SET node=42 WHERE building='6902' AND property='Mansions'
UPDATE customer_address SET node=42 WHERE building='6904' AND property='Mansions'
UPDATE customer_address SET node=42 WHERE building='6906' AND property='Mansions'
UPDATE customer_address SET node=42 WHERE building='6908' AND property='Mansions'
UPDATE customer_address SET node=42 WHERE building='6910' AND property='Mansions'
UPDATE customer_address SET node=42 WHERE building='6912' AND property='Mansions'
UPDATE customer_address SET node=42 WHERE building='6914' AND property='Mansions'
UPDATE customer_address SET node=42 WHERE address like '6902 HEMINGWAY%'
UPDATE customer_address SET node=42 WHERE address like '6904 HEMINGWAY%'
UPDATE customer_address SET node=42 WHERE address like '6906 HEMINGWAY%'
UPDATE customer_address SET node=42 WHERE address like '6908 HEMINGWAY%'
UPDATE customer_address SET node=42 WHERE address like '6910 HEMINGWAY%'
UPDATE customer_address SET node=42 WHERE address like '6912 HEMINGWAY%'
UPDATE customer_address SET node=42 WHERE address like '6914 HEMINGWAY%'
UPDATE customer_address SET node=5 WHERE building=5881 AND property like 'Sun P%'
UPDATE customer_address SET node=5 WHERE building=5891 AND property like 'Sun P%'
UPDATE customer_address SET node=5 WHERE building=5931 AND property like 'Sun P%'
UPDATE customer_address SET node=5 WHERE building=5941 AND property like 'Sun P%'
UPDATE customer_address SET node=5 WHERE building=5951 AND property like 'Sun P%'
UPDATE customer_address SET node=50 where building='1900'
UPDATE customer_address SET node=51 where building='1900' AND apartment LIKE '%A-%'
UPDATE customer_address SET node=52 where building='1900' AND apartment LIKE '%B-%'
UPDATE customer_address SET node=53 where building='1900' AND apartment LIKE '%C-%'
UPDATE customer_address SET node=54 where building='1900' AND apartment LIKE '%D-%'
UPDATE customer_address SET node=55 where building='1900' AND apartment LIKE '%E-%'
UPDATE customer_address SET node=56 where building='1900' AND apartment LIKE '%F-%'
UPDATE customer_address SET node=57 where building='1900' AND apartment LIKE '%G-%'
UPDATE customer_address SET node=58 where building='1900' AND apartment LIKE '%H-%'
UPDATE customer_address SET node=59 where building='1900' AND apartment LIKE '%I-%'
UPDATE customer_address SET node=6 WHERE building=5801 AND property like 'Sun P%'
UPDATE customer_address SET node=6 WHERE building=5861 AND property like 'Sun P%'
UPDATE customer_address SET node=6 WHERE building=5901 AND property like 'Sun P%'
UPDATE customer_address SET node=6 WHERE building=5911 AND property like 'Sun P%'
UPDATE customer_address SET node=6 WHERE building=5921 AND property like 'Sun P%'
UPDATE customer_address SET node=7 WHERE building=5703 AND property like 'Sun P%'
UPDATE customer_address SET node=7 WHERE building=5723 AND property like 'Sun P%'
UPDATE customer_address SET node=7 WHERE building=5743 AND property like 'Sun P%'
UPDATE customer_address SET node=7 WHERE building=5763 AND property like 'Sun P%'
UPDATE customer_address SET node=7 WHERE building=5871 AND property like 'Sun P%'
UPDATE customer_address SET node=8 WHERE building=5515 AND property like 'Sun P%'
UPDATE customer_address SET node=8 WHERE building=5525 AND property like 'Sun P%'
UPDATE customer_address SET node=8 WHERE building=5535 AND property like 'Sun P%'
UPDATE customer_address SET node=8 WHERE building=5545 AND property like 'Sun P%'
UPDATE customer_address SET node=8 WHERE building=5555 AND property like 'Sun P%'
UPDATE customer_address SET node=9 WHERE building=1173 AND property like 'Sun P%'
UPDATE customer_address SET node=9 WHERE building=1193 AND property like 'Sun P%'
UPDATE customer_address SET node=9 WHERE building=1233 AND property like 'Sun P%'
UPDATE customer_address SET node=9 WHERE building=1253 AND property like 'Sun P%'
UPDATE customer_address SET node=0 WHERE node IS NULL;
